### ISSUE TITLE
Update for XBMC 13?

### ISSUE THREAD

**Issue by josephby** [jhsrennie/MCERemote#1]
Any chance you could update this for XBMC 13 and submit it to the add-on repository?

**Comment by jhsrennie** [comment]
Hi Joseph,

I did update MCERemote and it is in the repository.

If you used a beta version of Githam it's possible MCERemote is marked as
disabled. I think the easy way to fix this is to delete the repository
database, then when you next start XBMC it will be recreated. The file is
(on Win7) 

C:\Users<username>\AppData\Roaming\XBMC\userdata\Database\Addons16.db

JR

**Comment by josephby** [comment]
Hrm. I tried that, and MCE Remote still wasn't in AddOns > Programs. I'm using Gotham on raspberrypi .

I'll do more to make sure that my AddOns are being updated correctly though.

**Comment by jhsrennie** [comment]
> I'm using Gotham on raspberrypi 

Aha! The add-on is tagged as Windows only.

**Comment by josephby** [comment]
Ahh! Sorry about that. I’m using xbmc with a Media Center IR receiver and remote that I salvaged from an old Windows machine. It works fine, but I was hoping to use your add-on to re-map some keys so that I have a working Zoom and Aspect Ratio button.

**Comment by jhsrennie** [comment]
Sadly the key remapping works by tweaking the registry settings that the MCE
remote driver uses. This wouldn't work on a Linux system.

JR
