### ISSUE TITLE
Kodi 19 - Marix

### ISSUE THREAD

**Issue by Tim-Ayling** [jhsrennie/MCERemote#4]
Sorry to be a pain, I’m using Kodi Matrix with a Media Center IR receiver and remote. I have three of these in constant use and several more spare (been using them since 2003 with XP Media Centre Edition, then Media Portal).
For various reasons want to now get serious with Kodi, but the better half is seriously (and rightly) complaining that we can longer use the 'i' button to access the context menu to delete Recorded TV or set TV Episodes to Watch/Unwatched.

Apparently it is lines that say 'WindowsError, e' that are no longer recognised by Python 3. Might as well be Chinese to me, but I can post you a log if you are happy to help.

**Comment by jhsrennie** [comment]
Hi Tim,

 

Do you mean the MCERemote add-on isn’t working with the current builds of Kodi?

 

JR

 

From: Tim-Ayling ***@***.*** 
Sent: 14 March 2021 00:17
To: jhsrennie/MCERemote
Cc: Subscribed
Subject: [jhsrennie/MCERemote] Kodi 19 - Marix (#4)

 

Sorry to be a pain, I’m using Kodi Matrix with a Media Center IR receiver and remote. I have three of these in constant use and several more spare (been using them since 2003 with XP Media Centre Edition, then Media Portal).
For various reasons want to now get serious with Kodi, but the better half is seriously (and rightly) complaining that we can longer use the 'i' button to access the context menu to delete Recorded TV or set TV Episodes to Watch/Unwatched.

Apparently it is lines that say 'WindowsError, e' that are no longer recognised by Python 3. Might as well be Chinese to me, but I can post you a log if you are happy to help.

**Comment by Tim-Ayling** [comment]
Hi JR,

That’s right.

First error:

Won’t load because of wrong Python requirement. MCERemote wants Python 2.1.0. Matrix requires Python 3.0.0.

Second Error:

Change Python to 3.0.0 in your addon.xml.
MCERemote loads, but if you try to use ‘Open’ you get the second error log above.
On Win10 it’s less verbose, but highlights ‘WindowsError, e:’ as the first line it stops at.


Tim

**Comment by jhsrennie** [comment]
Tim, I have got it mostly working but there is a problem with the Python 3 registry module that I haven't solved yet. Watch this space.

**Comment by Tim-Ayling** [comment]
John,

Impressed to say the least.

I am running it on Win7 and Win10 so can test both when you’re ready.

The log results I got were different because of different settings on each platform.

**Comment by jhsrennie** [comment]
Python 3 changed the module that is used to write to the registry in Windows, and the code that used to work is now giving me an error that I cannot find documented anywhere. I suspect it's going to be a matter of messing around until I can get it to work.

**Comment by Tim-Ayling** [comment]
Does this help :-

https://docs.python.org/3/library/winreg.html

**Comment by jhsrennie** [comment]
Tim, I have it working on Matrix but the settings dialog is a bit messed up. If you want to try it while I'm figuring out what's wrong you can install it from a zip file. You'll need to uninstall the addon (if you've manually installed it anywhere) and then install from this zip file:

[mceremote.zip](https://github.com/jhsrennie/MCERemote/files/6148529/mceremote.zip)

**Comment by Tim-Ayling** [comment]
Thanks John.

It has installed OK (had to use ‘run as admin’ on Win10 – haven’t tried Win7 yet.

However, it doesn’t do what we expected. In TV Series, the i button just brings up the Series Information, whereas we expected it to to do the right-click equivalent, which permits setting Watched/Unwatched status etc. I guess that will be a setting I can configure.

But the BIG thing is that it still doesn’t (with or without MCERemote) do triple-tap. I have a lot of films, and going to the first letter of the film and scanning forward or the next letter and scanning backwards takes ages.

We’ve had triple-tap since ‘XP Media Centre Edition’ and it’s still supported in MediaPortal (1 and 2), so where’d it go?

Sorry, shouldn’t annoy you, you have made the changes to MCERemote in an amazing time. Many thanks.
Tim

**Comment by Tim-Ayling** [comment]
New Zip also works fine with Win7.

On both, Configure Option just brings up a list of key-presses without telling you what they are for (I think that’s what you were referring to).

Option ‘Edit keyboard.xml’ asks ‘Do you want to update....’ Yes returns the error ‘Unidentified Error connecting to SourceForge’.

**Comment by jhsrennie** [comment]
Thanks, yes the fact the settings only shows you a list of keypresses is the problem, but I think I have found the bug so I'll be able to fix it.

The failing keymap editor download I know about. I'll look at that when I've fixed the settings.

Re triple tap: it's not obvious to me how this relates to MCERemote. All MCERemote does is configure your remote to send the keypress of your choice.

**Comment by jhsrennie** [comment]
Tim, try this. It should now be fully working.
[mceremote.zip](https://github.com/jhsrennie/MCERemote/files/6150133/mceremote.zip)

**Comment by Tim-Ayling** [comment]
Sorry I’ve been awhile John.

Couldn’t get letters to respond any which way after what you had said. So checked – Kodi Matrix on Win7 doesn’t respond to the letter keys at all. Just gives me numbers. I’ll investigate that later.

Moved to Win10 machine. MCERemote all working, thank you vey much – including configuration page.

The other problems are mine, I think.

**Comment by jhsrennie** [comment]
Excellent news, thanks :-)
I'll submit the updated version to the Kodi repository.

**Comment by Tim-Ayling** [comment]
> Excellent news, thanks :-)
> I'll submit the updated version to the Kodi repository.

Perhaps under the 'Read the instructions' (Option 1), you could add that if you make changes via the Key editor you must reboot for changes to take effect too.

**Comment by Tim-Ayling** [comment]
Perhaps under the 'Read the instructions' (Option 1), you could add that if you make changes via the Key editor you must reboot for changes to take effect too.
